name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.4.app
    - uses: actions/checkout@v2
      
    - name: Build and test iOS
      run: xcodebuild clean build test -workspace Investments.xcworkspace -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.5" -disableAutomaticPackageResolution
